# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/edwin/code/mnist-digits-as-stroke-sequences

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/edwin/code/mnist-digits-as-stroke-sequences

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/edwin/code/mnist-digits-as-stroke-sequences/CMakeFiles /home/edwin/code/mnist-digits-as-stroke-sequences/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/edwin/code/mnist-digits-as-stroke-sequences/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named createdata

# Build rule for target.
createdata: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 createdata
.PHONY : createdata

# fast build rule for target.
createdata/fast:
	$(MAKE) -f CMakeFiles/createdata.dir/build.make CMakeFiles/createdata.dir/build
.PHONY : createdata/fast

connectedComponents/connectedComponents.o: connectedComponents/connectedComponents.cpp.o

.PHONY : connectedComponents/connectedComponents.o

# target to build an object file
connectedComponents/connectedComponents.cpp.o:
	$(MAKE) -f CMakeFiles/createdata.dir/build.make CMakeFiles/createdata.dir/connectedComponents/connectedComponents.cpp.o
.PHONY : connectedComponents/connectedComponents.cpp.o

connectedComponents/connectedComponents.i: connectedComponents/connectedComponents.cpp.i

.PHONY : connectedComponents/connectedComponents.i

# target to preprocess a source file
connectedComponents/connectedComponents.cpp.i:
	$(MAKE) -f CMakeFiles/createdata.dir/build.make CMakeFiles/createdata.dir/connectedComponents/connectedComponents.cpp.i
.PHONY : connectedComponents/connectedComponents.cpp.i

connectedComponents/connectedComponents.s: connectedComponents/connectedComponents.cpp.s

.PHONY : connectedComponents/connectedComponents.s

# target to generate assembly for a file
connectedComponents/connectedComponents.cpp.s:
	$(MAKE) -f CMakeFiles/createdata.dir/build.make CMakeFiles/createdata.dir/connectedComponents/connectedComponents.cpp.s
.PHONY : connectedComponents/connectedComponents.cpp.s

createInputData/createInputData.o: createInputData/createInputData.cpp.o

.PHONY : createInputData/createInputData.o

# target to build an object file
createInputData/createInputData.cpp.o:
	$(MAKE) -f CMakeFiles/createdata.dir/build.make CMakeFiles/createdata.dir/createInputData/createInputData.cpp.o
.PHONY : createInputData/createInputData.cpp.o

createInputData/createInputData.i: createInputData/createInputData.cpp.i

.PHONY : createInputData/createInputData.i

# target to preprocess a source file
createInputData/createInputData.cpp.i:
	$(MAKE) -f CMakeFiles/createdata.dir/build.make CMakeFiles/createdata.dir/createInputData/createInputData.cpp.i
.PHONY : createInputData/createInputData.cpp.i

createInputData/createInputData.s: createInputData/createInputData.cpp.s

.PHONY : createInputData/createInputData.s

# target to generate assembly for a file
createInputData/createInputData.cpp.s:
	$(MAKE) -f CMakeFiles/createdata.dir/build.make CMakeFiles/createdata.dir/createInputData/createInputData.cpp.s
.PHONY : createInputData/createInputData.cpp.s

readImages/readMNISTImages.o: readImages/readMNISTImages.cpp.o

.PHONY : readImages/readMNISTImages.o

# target to build an object file
readImages/readMNISTImages.cpp.o:
	$(MAKE) -f CMakeFiles/createdata.dir/build.make CMakeFiles/createdata.dir/readImages/readMNISTImages.cpp.o
.PHONY : readImages/readMNISTImages.cpp.o

readImages/readMNISTImages.i: readImages/readMNISTImages.cpp.i

.PHONY : readImages/readMNISTImages.i

# target to preprocess a source file
readImages/readMNISTImages.cpp.i:
	$(MAKE) -f CMakeFiles/createdata.dir/build.make CMakeFiles/createdata.dir/readImages/readMNISTImages.cpp.i
.PHONY : readImages/readMNISTImages.cpp.i

readImages/readMNISTImages.s: readImages/readMNISTImages.cpp.s

.PHONY : readImages/readMNISTImages.s

# target to generate assembly for a file
readImages/readMNISTImages.cpp.s:
	$(MAKE) -f CMakeFiles/createdata.dir/build.make CMakeFiles/createdata.dir/readImages/readMNISTImages.cpp.s
.PHONY : readImages/readMNISTImages.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... createdata"
	@echo "... connectedComponents/connectedComponents.o"
	@echo "... connectedComponents/connectedComponents.i"
	@echo "... connectedComponents/connectedComponents.s"
	@echo "... createInputData/createInputData.o"
	@echo "... createInputData/createInputData.i"
	@echo "... createInputData/createInputData.s"
	@echo "... readImages/readMNISTImages.o"
	@echo "... readImages/readMNISTImages.i"
	@echo "... readImages/readMNISTImages.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

